from ._1_FCN import FCN
from ._2_UNet import UNet
from ._3_SegNet import SegNet
from ._4_Deeplab import DeepLabV3Plus
from ._5_PSPNet import PSPNet
from ._11_ENet import ENet
from ._12_LinkNet import LinkNet
from ._13_ICNet import ICNet
from ._14_BiseNet import BiSeNet
from ._15_DFANet import DFANet